### ISSUE TITLE
Please review my Problem Statement document

### ISSUE THREAD

**Issue by Ao99** [Ao99/CAS741#1]
@smiths 
Please take a review of the following [document](https://github.com/Ao99/CAS741/blob/master/docs/ProblemStatement/ProblemStatement.pdf)

**Comment by smiths** [comment]
Looks good @Ao99.  I approve your project for CAS 741.  The problem statement itself could use a few tweaks.  I suggest that you make the following edits:

- work in the word library, since your focus will be on a library that provides medical image processing services
- work in the word family, since you aren't thinking about just one use of the library, you are trying to anticipate many potential uses
- review the writing checklist under LaTeX, where it mentions the period that does not end a sentence (Dr. Smith, Dr. Carette).  The spacing as given is too large.  (You want 1 space, not 2.)
- add Dr. Noseworthy as a stakeholder (https://www.eng.mcmaster.ca/people/faculty/michael-noseworthy)

**Comment by Ao99** [comment]
Revised as suggested.

**Comment by smiths** [comment]
Looks good @Ao99.  For next time, please include the hash of the commit the closes the issue in your comment.  In this case, the commit is: a82c833cd02e1b39687576145c787a06178dd67f
