### ISSUE TITLE
VnV Issue#5 Portability verification 

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#23]
Hi Ao,

In section **5.2.6 Portability**, you listed portabilities on Windows, Mac and Linux, but your initial state is that MISEG is successfully installed on virtual machine on these 3 systems. I wonder that, if you are just running it on virtual machine, you should test the portability on different virtual machines such as Parallels Desktop, Oracle VM Virtualbox, VMware Workstation Player, etc.,  but not operation systems. 

@smiths  What do you think?

**Comment by smiths** [comment]
@best-zhang-zhi, I do not think that @Ao99 intends for MISEG to always be run on a virtual machine.  I believe that VMs are mentioned because he doesn't have access to the hardware for all of the portability tests.  A VM is also nice because the default has nothing special installed, which avoids the "but it works on my computer" problem.  I don't think @Ao99 wants to go so far to check different VMs of the same OS.  Having said that, it would make your test more specific @Ao99 if you said what VMs you are planning on using.

**Comment by Ao99** [comment]
MISEG is not intended to always run on a virtual machine. It has been specified that what VMs are going to be used for testing.
