### ISSUE TITLE
MIS Issue 4

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#43]
I saw that you have a table for possible Exceptions in section 13 Appendix, in 8.4.4, you listed FileError exception, for consistency, you can just have exc:= FileError, and then write the related error in the appendix. 
![Screen Shot 2019-11-28 at 7 46 54 PM](https://user-images.githubusercontent.com/55267358/69836624-12ac0580-1218-11ea-8ac1-c5ed42f78c33.png)

**Comment by Ao99** [comment]
I did this because I didn't find this FileError listed in the appendix of SWHS. My assumption is that whatever system we use, the system will provide this exception.

After the implementation, I decided to have two separate exceptions "the file names cannot be found" and "the format of inputFile is incorrect" and describe both of them with my own words in the appendix.
@smiths what do you think?

**Comment by smiths** [comment]
@Ao99, I used to label all exceptions with project specific names, but I've found that using common exception names makes the implementation easier.  Although the MIS should be programming language agnostic, if you use exception names that match your planned implementation, it makes things a bit easier.  For instance, if Python is going to be used, then the exception valueError is handy, since many MIS exceptions are really value errors.

This is a long way of saying that I'm fine with either approach.  If implementing custom named exceptions becomes a headache though, you can might want to switch to using exception names in your MIS that match your programming language of choice.

**Comment by Ao99** [comment]
@smiths 
As for this error "FileError", it's not listed in the Appendix of SWHS. What's your reason for not including it?

As for the naming convention, I just adopted your way from SWHS. I named most errors as "badXxx"
, "emptyXxxxx".

**Comment by smiths** [comment]
@Ao99, there wasn't any reason for not including FileError in the Appendix.  It could definitely be included in the Appendix.

**Comment by Ao99** [comment]
Separated the exception to "the file names cannot be found" and "the format of inputFile is incorrect" and describe both of them with my own words in the appendix.
