### ISSUE TITLE
MIS issue5

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#44]
Hi Ao,
in section 9.4.3 Assumptions, I think this is not an assumption, because this is the constraint, and it has been covered in the exception part of the ImageData(x,y,p).

**Comment by Ao99** [comment]
The meaning of this assumption is that "Since I assume we only use X such that 10<X<1000, I can put such a constraint to X". In the real computing world, X (the width of an image) can actually be less than 10, or much bigger than 1000. Without this assumption, my constraints make no sense.

However, I've decided to remove the assumption and constraints together. So as long as an image has width and height greater than 0, it is allowed.
