### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sharyuwu** [Ao99/CAS741#47]
![image](https://user-images.githubusercontent.com/55363335/70763236-6f7fe380-1d21-11ea-9388-8cb5222727e7.png)

It is an interesting choice to make constant values as an input module.
The question is does this module related to the requirement or this is an assumption under others module.
If this is not really a module that just providing constant value to other modules maybe it need a different name?

**Comment by Ao99** [comment]
I don't quite understand your comment as "an input module", but this module is not an input module.
It stores and provides constant values that can be changed by the programmer but not the users. I don't think it needs any changes.

But thanks for putting a picture here, so that I found a mistake by myself. The values are not secret to the users. Actually the software asks users to make a choice from these values. So I'll change the secret to "The way storing and modifying the constant values".

**Comment by sharyuwu** [comment]
After you make the changed of the secret to the new line, it makes more sense to this module.
However, I still recommend rethinking if you really need this module.
The reason I said was the same reason that Dr. Smith put down in your MIS:)
