### ISSUE TITLE
Implementation review

### ISSUE THREAD

**Issue by Ao99** [Ao99/CAS741#50]
Unit test plan and reports not done yet.

Implementation is done (faked input with .bmp image inputs) and tested on Windows macOS and Linux. 

Could you please take a look? So I might be able to fix it before the 18th if it doesn't run on your machine.

The instruction is [here](https://github.com/Ao99/MISEG/blob/master/src/INSTALL.pdf).

**Comment by smiths** [comment]
@Ao99, I had a look at your instructions for installation.  Is it possible that your program can be run without an IDE?  I prefer to use javac at the command line.  Ideally there would be a makefile that would only require calling make.  There would be a separate rule in the makefile for "making" the test cases.

If this is too much work to accomplish, I'll install an IDE.

**Comment by Ao99** [comment]
@smiths It definitely should work with Javac without an IDE, because I tested with Javac on Windows and Linux.

I updated the [instruction](https://github.com/Ao99/MISEG/blob/master/src/INSTALL.pdf). Please go to **1.2 Test and Run with the Command Line** on page 4.

As for makefile, I don't think that I will have time to do it before the deadline. But it's something interesting to do after the deadline.

**Comment by smiths** [comment]
Thank you for the instructions @Ao99.  I was able to run your code and reproduce the results that you expected.   I have some feedback as follows:

- In the introduction to your instructions, make it clear that there are two versions - one for an IDE and one for the command line
- Is it possible to use a relative path for the input and output files so that the user doesn't have to edit the source code?
- If you have time, please port your tests to JUnit.  With JUnit you would no longer have to manually check the test cases.  JUnit can determine whether the expected exception was generated, for some of your error test cases.

**Comment by Ao99** [comment]
@smiths 
Thank you for your feedback.
- I'll make the changes
- Since it is a library, I expect the users to change the Main.java anyway. However, for the convenience of the first test, I agree with you that I should make the relative path work for the Javac method. I think there is a way of doing that, but it will change my Input module a lot. I will think about it later.
- I think that's something I'll do after the deadline.
Closing this issue. I'll submit another issue for the final review.

**Comment by smiths** [comment]
@Ao99, rather than worry about Main.java, your test cases can become the library driver.  The test cases will not use Main.  If you add unit testing, then the tests can know the location of the files.  My advice would be to focus on the command line interface for unit testing.  Don't worry about getting it to work in an IDE.

**Comment by Ao99** [comment]
@smiths 
Good suggestions, thank you. I'm reopening this issue and I'll try to do it this winter.
