### ISSUE TITLE
4.1 user responsibilities redundancy

### ISSUE THREAD

**Issue by peter-michalski** [Ao99/CAS741#8]
I think "ensuring no errors in the data entry" can be removed from the first user responsibilities. 
My reasoning is as follows:
1) it can be assumed that the user takes care to input correct data
2) the second user responsibility partially covers this
3) the line  "ensuring no errors in the data entry" makes it seem to me that the system will fail ungracefully if the user inputs incorrect data - which we know should not be the case since one of the FR's is input checking

**Comment by Ao99** [comment]
I agree, revised

**Comment by smiths** [comment]
@Ao99, the software should automatically detect some kinds of errors (like entering 1.x, instead of 1.3), but there is still an element of user responsibility for input.  If the user is asked to enter the length of their desk and they make a mistake with the measurement, there is no way for the software to know.  For a medical image, if the user sends a valid file, but the wrong file, the software can't really know.  The user still has to take some responsibility.
